{
  "comments": [
    {
      "key": {
        "uuid": "5ac10518_dd31a0a3",
        "filename": "modules/opnfv/utils/OPNFVExceptions.py",
        "patchSetId": 2
      },
      "lineNbr": 115,
      "author": {
        "id": 2175
      },
      "writtenOn": "2016-11-21T07:13:53Z",
      "side": 1,
      "message": "not",
      "range": {
        "startLine": 115,
        "startChar": 19,
        "endLine": 115,
        "endChar": 22
      },
      "revId": "d64f54d118fde792b3850feab31e839479a0a9be",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}